name: SpawnCMDPlugin
version: 0.0.1
main: io.maloschnikow.spawncmdplugin.SpawnCMDPlugin
description: Adds a "/spawn" command to teleport the player back to the spawn.
author: Maloschnikow
api-version: '1.21.1'

commands:
  spawn:
    description: "Teleports the player back to spawn."
    usage: "/spawn"
