name: spawncmdplugin
version: 1.4.2
main: io.maloschnikow.spawncmdplugin.SpawnCMDPlugin
description: Adds a "/spawn" command to teleport the player back to the spawn.
author: Maloschnikow
api-version: '1.21.1'

permissions:
  permissions.setspawnlocation:
    description: "Allows someone to use the /setspawnlocation command."
    default: op